version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://root:M1a1p1l1e!@db:3306/training_db

  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0
    container_name: training_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: M1a1p1l1e!
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password1!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
